---
title: "Final Project"
authors: "Kim Mincin $ Drew Insley"
due date: "April 30, 2019"
output: html_notebook
---

## Front Matter

```{r message=FALSE, warning=FALSE}
# clear enviornment
rm(list = ls())

# download packages
library(mdsr)
library(rvest)
library(readr)
library(tidyr)

# read data
page <- "http://worldpopulationreview.com/countries/suicide-rate-by-country/"
xpath <- '//*[@id="__next"]/div/div[1]/div[2]/div[1]/div/div[2]/div/div/table'
table_list <- 
  page %>%
  read_html() %>%
  html_nodes(xpath = xpath) %>%
  html_table(fill = TRUE)
Suicide <- table_list[[1]]

Happiness <- read.csv("2017_Happiness.csv")

Happy_Suicide <- 
  Happiness %>%
  left_join(Suicide, by = c("Country" = "X1"))
```


## Project

```{r}
# clean data
Happy_Suicide_Clean <-
  Happy_Suicide %>%
  rename(country = Country,
         happiness_rank = Happiness.Rank,
         happiness_score = Happiness.Score,
         maximum_happiness = Whisker.high,
         minimum_happiness = Whisker.low,
         GDP_per_capita = Economy..GDP.per.Capita.,
         family = Family,
         life_expectancy = Health..Life.Expectancy.,
         freedom = Freedom,
         generosity = Generosity,
         corruption = Trust..Government.Corruption.,
         suicides = X2,
         suicide_rank = X3) %>%
  mutate(suicides = as.numeric(gsub("suicides per 100k", " ", suicides)),
         suicide_rank = as.numeric(suicide_rank))

Happy_Suicide_Clean[12] <- NULL

Happy_Suicide_Clean
```

```{r}
# dendogram of countries
Happy_Suicide_Clean_2 <- Happy_Suicide_Clean[-c(1)]

Happy_Suicide_Clean_2 <-
  Happy_Suicide_Clean_2 %>%
  select(happiness_rank, GDP_per_capita, life_expectancy, generosity, freedom) %>%
  arrange(happiness_rank) %>%
  head(25)
  

Happy_std <-
  scale(Happy_Suicide_Clean_2) %>%
  as.data.frame()

Happy_dist <- 
  dist(Happy_std)

Happy_dendo <-
  Happy_dist %>%
  hclust(method = "complete")

Happy_Suicide_Clean_Top_25 <- 
  Happy_Suicide_Clean %>%
  arrange(happiness_rank) %>%
  head(25)

labels <- Happy_Suicide_Clean_Top_25$country

Happy_dendo %>%
  plot(cex = 0.9, labels = labels, lwd = 2,
       main = "Top 25 Happiest Countries Dendogram")
```

```{r}
# create linear model
Happy_Suicide_Clean %>%
  ggplot(aes(x = GDP_per_capita, y = happiness_score)) +
  geom_smooth(method = "lm", se = FALSE, color = "dark red") +
  geom_point(color = "dark blue") +
  xlab("GDP Per Capita") +
  ylab("Happiness Score") +
  ggtitle("Predicting Happiness Score from GDP Per Capita") +
  annotate("text", x = .4, y = 7, label = "y = 2.1842x + 3.2032", size = 7.5, color = "dark red") +
  theme(plot.background = element_rect(fill = 'grey'),
        plot.title = element_text(size = 17.5, lineheight = .8, vjust = 1, family = "", face = "bold"),
        panel.background = element_rect(fill = 'grey'),
        panel.grid.major = element_line(color = "white"),
        panel.grid.minor = element_line(color = "grey"))
```

```{r}
# summary of the linear model
Mod1 <- lm(happiness_score ~ GDP_per_capita, data = Happy_Suicide_Clean)
msummary(Mod1)
```

```{r}
# show the residuals
mod_values <- 3.2032 + (2.1842 * Happy_Suicide_Clean$GDP_per_capita)

Happy_Dist <-
  Happy_Suicide_Clean %>%
  select(country, happiness_score) %>%
  mutate(model_values = mod_values,
         residuals = happiness_score - model_values)

Happy_Dist %>%
  ggplot(aes(x = model_values, y = residuals)) +
  geom_point(color = 'dark blue') +
  geom_hline(yintercept = 0, color = 'dark red') +
  xlab("Fitted Values") +
  ylab("Residuals") +
  ggtitle("Residual Plot") +
  annotate("text", x = 6.5, y = 2, label = "RMS Error = 0.66", size = 7.5, color = "dark red") +
  theme(plot.background = element_rect(fill = 'grey'),
        plot.title = element_text(size = 20, lineheight = .8, vjust = 1, family = "", face = "bold"),
        panel.background = element_rect(fill = 'grey'),
        panel.grid.major = element_line(color = "white"),
        panel.grid.minor = element_line(color = "grey"))

sqrt(mean(Happy_Dist$residuals ^ 2))
```












